def course(COURSE):
    print("course is",COURSE)
def validity(VALIDITY):
    print("validity is",VALIDITY)
def blood(BLOOD):
    print("Blood group is",BLOOD)
def contact(CONTACT):
    print("contact :",CONTACT)
def aadhar(AADHAR):
    print("aadhar  :",AADHAR)
COURSE=input("COURSE: ")
VALIDITY=input("VALIDITY: ")
BLOOD=input("BLOOD: ")
CONTACT=input("CONTACT: ")
AADHAR=input("AADHAR: ")
course(COURSE)
validity(VALIDITY)
blood(BLOOD)
contact(CONTACT)
aadhar(AADHAR)










def details(name,place,branch):
    print("Hi all!\n My name is",name,"\nI'm from",place,"\n\I'm Studying Bachelor of Technology in the stream of",branch,
"at SRIT,anantapur.")
name=input("Enter your name:")
name=input("Enter your place:")
name=input("Enter your branch:")
details(name,place,branch)





